name: "Streatham & Brixton Chess Club"
shortname: "S&BCC"
url: "http://streathamchess.github.io"
exclude:
  - Gemfile
  - README.md
  - .notes
  - rakefile
markdown: kramdown
gems:
  - jekyll-sitemap
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post_with_comments"
      jq_disable: true
      firebase: true
