name: "Streatham & Brixton Chess Club"
shortname: "S&BCC"
url: "http://streathamchess.github.io"
exclude:
  - Gemfile
  - README.md
  - .scripts
  - .notes
markdown: kramdown
gems:
  - jekyll-sitemap
