name: "Streatham & Brixton Chess Club"
shortname: "S&BCC"
url: "http://streathamchess.github.io"
exclude:
  - Gemfile
  - README.md  
  - .notes
  - rakefile
markdown: kramdown
gems:
  - jekyll-sitemap
